#!/usr/bin/env bash

set -e

if [ $# -ne 2 ]; then
    echo "Usage: $0 root file"
    exit 1
fi

path() {
    if [[ "$(dirname $1)" == "." ]]; then
        echo
    else
        echo $(dirname $1)/
    fi
}

enter() {
    ROOT=$1
    FILE=$2
    DEPS=$(sed -nr 's/^`include "(.*\.v)"$/\1/p' $FILE | tr '\n' ' ')

    if [ -z "$DEPS" ]; then
        return
    fi

    echo -n "$ROOT: "
    for DEP in $DEPS; do
        echo -n "$(path $FILE)$DEP "
    done
    echo

    for DEP in $DEPS; do
        enter $ROOT $(path $FILE)$DEP
    done
}

enter $1 $2
